"""Lambda behind the Gateway target: Brightwell's orders, one tool.

The gateway invokes this with the tool's arguments as the event. list_orders
takes a customer_id and returns that customer's orders. Post 02's by-id
lookup_order is gone from this demo, it answered for any customer to whoever
held the agent's token, and from post 05 on every question is asked on
behalf of a known customer.

orders.csv is the system of record the series shares from post 04 on. It
is generated by scripts/make_orders.py and packaged into the zip with this
file, so the Lambda reads it from its own directory.
"""

import csv
import pathlib

ORDERS_CSV = pathlib.Path(__file__).with_name("orders.csv")
_orders = None


def orders():
    global _orders
    if _orders is None:
        with ORDERS_CSV.open(newline="") as fh:
            _orders = {row["order_id"]: row for row in csv.DictReader(fh)}
    return _orders


def _public(row):
    """What a caller is allowed to see. customer_id stays server-side."""
    return {
        "order_id": int(row["order_id"]),
        "placed_at": row["placed_at"],
        "items": int(row["items"]),
        "total": float(row["total"]),
        "status": row["status"],
        "carrier": row["carrier"] or None,
        "eta": row["eta"] or None,
    }


def list_orders(customer_id):
    mine = [_public(r) for r in orders().values() if r["customer_id"] == customer_id]
    return {"customer_id": customer_id, "orders": sorted(mine, key=lambda o: o["order_id"])}


def handler(event, context):
    if "customer_id" in event:
        return list_orders(str(event["customer_id"]))
    return {"error": "expected customer_id"}
